import AxeBuilder from '@axe-core/playwright';
import { expect, test } from '@playwright/test';

test('seeded dashboard exposes clear, accessible signals', async ({ page }) => {
  await page.goto('/dashboard');
  await expect(page.getByRole('heading', { level: 1, name: 'Good morning, Jordan' })).toBeVisible();
  await expect(page.getByText('Overall response rate')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Next best actions' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'IBM Bob workflow' })).toBeVisible();

  const results = await new AxeBuilder({ page }).disableRules(['color-contrast']).analyze();
  expect(results.violations.filter((violation) => violation.impact === 'critical')).toEqual([]);
});

test('user can preview and validate a governed sheet fixture', async ({ page }) => {
  await page.goto('/integrations/google-sheets');
  await expect(page.getByRole('heading', { level: 1, name: 'Google Sheets' })).toBeVisible();
  await page.getByRole('button', { name: 'Preview and validate' }).click();
  await expect(page.getByText('Preview complete with two decisions')).toBeVisible();
  await expect(page.getByText('Invalid email', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Run dry sync' }).click();
  await expect(page.getByText('Dry-run result')).toBeVisible();
});

test('generation request stops in Awaiting IBM Bob without a runtime', async ({ page }) => {
  await page.goto('/follow-ups?task=fu_maya');
  await expect(page.getByRole('heading', { level: 2, name: 'Maya Chen' })).toBeVisible();
  await page.getByRole('button', { name: 'Generate with IBM Bob' }).click();
  await expect(page.getByRole('heading', { name: 'Waiting for IBM Bob' })).toBeVisible();
  await expect(page.getByText('Generated by IBM Bob')).toHaveCount(0);
  await expect(page.getByText('Awaiting IBM Bob').first()).toBeVisible();
});

test('demo draft remains editable and approval does not send', async ({ page }) => {
  await page.goto('/follow-ups?task=fu_amara');
  await expect(
    page.getByText('This deterministic fixture demonstrates the review experience.'),
  ).toBeVisible();
  await page.getByLabel('Subject').fill('Reviewed community impact details');
  await page.getByRole('button', { name: 'Approve demo draft' }).click();
  await expect(page.getByText('Approved for manual delivery')).toBeVisible();
  await expect(page.getByText('No external message was sent.')).toBeVisible();
});

test('user can complete an internal follow-up without triggering outreach', async ({ page }) => {
  await page.goto('/follow-ups?task=fu_amara');
  await page.getByRole('button', { name: 'Complete', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Complete follow-up for Amara Okafor?' });
  await expect(dialog).toBeVisible();
  await dialog.getByRole('button', { name: 'Complete follow-up' }).click();
  await expect(page.getByText('Follow-up completed.')).toBeVisible();
  await expect(page.locator('.followup-detail__header').getByText('Completed')).toBeVisible();
});

test('contact recommendation exposes reasons and algorithm provenance', async ({ page }) => {
  await page.goto('/contacts/ct_amara_okafor');
  await expect(page.getByRole('heading', { level: 1, name: 'Amara Okafor' })).toBeVisible();
  await expect(page.getByText('faro-window-v1.0.0')).toBeVisible();
  await expect(page.getByText('CONTACT_REPLY_PATTERN')).toBeVisible();
});

test('follow-up center has no critical accessibility violations', async ({ page }) => {
  await page.goto('/follow-ups');
  const results = await new AxeBuilder({ page }).disableRules(['color-contrast']).analyze();
  expect(results.violations.filter((violation) => violation.impact === 'critical')).toEqual([]);
});
