ALTER TABLE "SheetConnection"
ADD COLUMN "readRange" TEXT NOT NULL DEFAULT 'A1:ZZ1001',
ADD COLUMN "headerRow" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "lastErrorCode" TEXT,
ADD COLUMN "lastErrorAt" TIMESTAMP(3);
