import type { DemoWorkspaceData } from './domain';

/**
 * A coherent, read-only product tour dataset. Every person, organization, and
 * message is fictional. Times are fixed so screenshots and tests remain stable.
 */
export const demoWorkspace: DemoWorkspaceData = {
  workspace: {
    id: 'ws-beacon-lab',
    name: 'Beacon Community Lab',
    slug: 'beacon-community-lab',
    defaultTimezone: 'America/Los_Angeles',
    quietHoursStart: '18:00',
    quietHoursEnd: '08:00',
    createdAt: '2026-01-08T17:00:00.000Z',
    updatedAt: '2026-07-10T15:00:00.000Z',
  },
  users: [
    {
      id: 'user-maya-chen',
      name: 'Maya Chen',
      email: 'maya.chen@example.test',
      timezone: 'America/Los_Angeles',
      initials: 'MC',
    },
    {
      id: 'user-julian-reed',
      name: 'Julian Reed',
      email: 'julian.reed@example.test',
      timezone: 'America/Denver',
      initials: 'JR',
    },
    {
      id: 'user-nadia-patel',
      name: 'Nadia Patel',
      email: 'nadia.patel@example.test',
      timezone: 'America/New_York',
      initials: 'NP',
    },
  ],
  memberships: [
    { workspaceId: 'ws-beacon-lab', userId: 'user-maya-chen', role: 'OWNER' },
    { workspaceId: 'ws-beacon-lab', userId: 'user-julian-reed', role: 'MANAGER' },
    { workspaceId: 'ws-beacon-lab', userId: 'user-nadia-patel', role: 'MEMBER' },
  ],
  dashboard: {
    rangeLabel: 'Last 6 weeks',
    asOf: '2026-07-10T15:00:00.000Z',
    metrics: [
      {
        id: 'outreach-sent',
        label: 'Outreach sent',
        value: '126',
        numericValue: 126,
        unit: 'COUNT',
        change: 12.5,
        changeLabel: 'vs. prior 6 weeks',
        trend: 'UP',
        status: 'ON_TRACK',
        description: 'Reviewed external outreach recorded across active campaigns.',
      },
      {
        id: 'overall-response-rate',
        label: 'Overall response rate',
        value: '38.9%',
        numericValue: 38.9,
        unit: 'PERCENT',
        change: 4.2,
        changeLabel: 'percentage points',
        trend: 'UP',
        status: 'CLEAR_SIGNAL',
        description: '49 responses from 126 outbound messages.',
      },
      {
        id: 'positive-response-rate',
        label: 'Positive response rate',
        value: '24.6%',
        numericValue: 24.6,
        unit: 'PERCENT',
        change: 2.8,
        changeLabel: 'percentage points',
        trend: 'UP',
        status: 'CLEAR_SIGNAL',
        description: 'Interested, information-requested, and meeting-requested responses.',
      },
      {
        id: 'follow-ups-due',
        label: 'Follow-ups due',
        value: '5',
        numericValue: 5,
        unit: 'COUNT',
        change: 2,
        changeLabel: 'need attention today',
        trend: 'UP',
        status: 'NEEDS_ATTENTION',
        description: 'Three overdue and two due before the workspace quiet-hours boundary.',
      },
      {
        id: 'average-response-time',
        label: 'Median response time',
        value: '5h 22m',
        numericValue: 322,
        unit: 'MINUTES',
        change: -48,
        changeLabel: 'minutes faster',
        trend: 'DOWN',
        status: 'CLEAR_SIGNAL',
        description: 'Median time from delivered outreach to first inbound response.',
      },
      {
        id: 'active-sponsorship-value',
        label: 'Active sponsorship value',
        value: '$480K',
        numericValue: 480000,
        unit: 'CURRENCY',
        change: 65000,
        changeLabel: 'new pipeline value',
        trend: 'UP',
        status: 'ON_TRACK',
        description: 'Unweighted value of active sponsor opportunities, excluding declined.',
      },
    ],
    responseRateTrend: [
      {
        period: 'Jun 1',
        outreachSent: 17,
        responses: 5,
        responseRate: 29.4,
        positiveResponseRate: 17.6,
      },
      {
        period: 'Jun 8',
        outreachSent: 19,
        responses: 7,
        responseRate: 36.8,
        positiveResponseRate: 21.1,
      },
      {
        period: 'Jun 15',
        outreachSent: 21,
        responses: 8,
        responseRate: 38.1,
        positiveResponseRate: 23.8,
      },
      {
        period: 'Jun 22',
        outreachSent: 20,
        responses: 8,
        responseRate: 40,
        positiveResponseRate: 25,
      },
      {
        period: 'Jun 29',
        outreachSent: 24,
        responses: 10,
        responseRate: 41.7,
        positiveResponseRate: 29.2,
      },
      {
        period: 'Jul 6',
        outreachSent: 25,
        responses: 11,
        responseRate: 44,
        positiveResponseRate: 28,
      },
    ],
    outreachHeatmap: [
      { day: 'Monday', hour: 9, responseRate: 34, sampleSize: 18, strength: 'MEDIUM' },
      { day: 'Monday', hour: 14, responseRate: 39, sampleSize: 13, strength: 'MEDIUM' },
      { day: 'Tuesday', hour: 9, responseRate: 46, sampleSize: 24, strength: 'HIGH' },
      { day: 'Tuesday', hour: 11, responseRate: 43, sampleSize: 21, strength: 'HIGH' },
      { day: 'Wednesday', hour: 10, responseRate: 41, sampleSize: 22, strength: 'HIGH' },
      { day: 'Wednesday', hour: 15, responseRate: 27, sampleSize: 11, strength: 'LOW' },
      { day: 'Thursday', hour: 9, responseRate: 44, sampleSize: 19, strength: 'HIGH' },
      { day: 'Thursday', hour: 13, responseRate: 36, sampleSize: 14, strength: 'MEDIUM' },
      { day: 'Friday', hour: 10, responseRate: 31, sampleSize: 16, strength: 'MEDIUM' },
      { day: 'Friday', hour: 15, responseRate: 18, sampleSize: 9, strength: 'LOW' },
    ],
    pipeline: [
      { stage: 'Prospecting', order: 1, organizationCount: 0, value: 0, weightedValue: 0 },
      { stage: 'Qualified', order: 2, organizationCount: 1, value: 90000, weightedValue: 22500 },
      { stage: 'Contacted', order: 3, organizationCount: 1, value: 150000, weightedValue: 60000 },
      { stage: 'Engaged', order: 4, organizationCount: 0, value: 0, weightedValue: 0 },
      { stage: 'Proposal', order: 5, organizationCount: 1, value: 180000, weightedValue: 117000 },
      {
        stage: 'Negotiation',
        order: 6,
        organizationCount: 1,
        value: 125000,
        weightedValue: 100000,
      },
      { stage: 'Committed', order: 7, organizationCount: 1, value: 60000, weightedValue: 60000 },
      { stage: 'Declined', order: 8, organizationCount: 1, value: 75000, weightedValue: 0 },
    ],
    campaignPerformance: [
      {
        campaignId: 'campaign-pacific-summit',
        campaignName: 'Pacific Community Summit 2026',
        outreachSent: 54,
        responseRate: 40.7,
        positiveResponseRate: 27.8,
        followUpsDue: 3,
      },
      {
        campaignId: 'campaign-partner-renewal',
        campaignName: 'Partner Renewal · Q3',
        outreachSent: 43,
        responseRate: 39.5,
        positiveResponseRate: 25.6,
        followUpsDue: 1,
      },
      {
        campaignId: 'campaign-speaker-series',
        campaignName: 'Community Leaders Speaker Series',
        outreachSent: 29,
        responseRate: 34.5,
        positiveResponseRate: 17.2,
        followUpsDue: 1,
      },
    ],
    nextBestActionIds: [
      'followup-elena-proposal',
      'followup-marcus-meeting',
      'followup-priya-materials',
      'followup-jon-checkin',
      'followup-lina-confirmation',
    ],
    recentActivity: [
      {
        id: 'activity-marcus-response',
        type: 'RESPONSE',
        title: 'Meeting requested by Marcus Lee',
        detail: 'Harbor Civic Foundation · Partner Renewal · Q3',
        occurredAt: '2026-07-10T14:18:00.000Z',
        status: 'Clear signal',
        href: '/contacts/contact-marcus-lee',
      },
      {
        id: 'activity-dry-run',
        type: 'SYNC',
        title: 'Sheet mapping dry run finished',
        detail: '84 rows validated; 2 require review; no records were written.',
        occurredAt: '2026-07-10T13:42:00.000Z',
        status: 'Review required',
        href: '/integrations/google-sheets',
      },
      {
        id: 'activity-demo-draft',
        type: 'DRAFT',
        title: 'Demo draft ready for Elena Ruiz',
        detail: 'Deterministic fixture · not generated by IBM Bob',
        occurredAt: '2026-07-10T12:05:00.000Z',
        status: 'Draft ready',
        href: '/follow-ups/followup-elena-proposal',
      },
      {
        id: 'activity-recommendation',
        type: 'RECOMMENDATION',
        title: 'High-confidence window calculated',
        detail: 'Tuesday 9:15 AM in Priya Nair’s timezone',
        occurredAt: '2026-07-10T11:30:00.000Z',
        status: 'Clear signal',
        href: '/contacts/contact-priya-nair',
      },
    ],
  },
  organizations: [
    {
      id: 'org-lumina-mobility',
      workspaceId: 'ws-beacon-lab',
      name: 'Lumina Mobility Cooperative',
      type: 'SPONSOR',
      industry: 'Accessible transportation',
      website: 'https://lumina.example.test',
      sponsorshipStage: 'Proposal',
      estimatedValue: 180000,
      weightedValue: 117000,
      interestAreas: ['Accessible transit', 'Community mobility', 'Volunteer activation'],
      tags: ['Summit sponsor', 'West coast'],
      decisionMakerContactIds: ['contact-elena-ruiz', 'contact-sam-rivera'],
      contactCount: 2,
      lastActivityAt: '2026-07-09T21:40:00.000Z',
    },
    {
      id: 'org-harbor-civic',
      workspaceId: 'ws-beacon-lab',
      name: 'Harbor Civic Foundation',
      type: 'NONPROFIT',
      industry: 'Community development',
      website: 'https://harborcivic.example.test',
      sponsorshipStage: 'Negotiation',
      estimatedValue: 125000,
      weightedValue: 100000,
      interestAreas: ['Neighborhood leadership', 'Youth programs'],
      tags: ['Renewal', 'Strategic partner'],
      decisionMakerContactIds: ['contact-marcus-lee'],
      contactCount: 1,
      lastActivityAt: '2026-07-10T14:18:00.000Z',
    },
    {
      id: 'org-orbit-learning',
      workspaceId: 'ws-beacon-lab',
      name: 'Orbit Learning Studio',
      type: 'SPONSOR',
      industry: 'Education technology',
      website: 'https://orbit-learning.example.test',
      sponsorshipStage: 'Qualified',
      estimatedValue: 90000,
      weightedValue: 22500,
      interestAreas: ['Digital access', 'Mentorship'],
      tags: ['New prospect', 'Education'],
      decisionMakerContactIds: ['contact-priya-nair'],
      contactCount: 1,
      lastActivityAt: '2026-07-08T16:32:00.000Z',
    },
    {
      id: 'org-verdant-grid',
      workspaceId: 'ws-beacon-lab',
      name: 'Verdant Grid Works',
      type: 'SPONSOR',
      industry: 'Community energy',
      website: 'https://verdant-grid.example.test',
      sponsorshipStage: 'Contacted',
      estimatedValue: 150000,
      weightedValue: 60000,
      interestAreas: ['Resilience', 'Climate education'],
      tags: ['Priority', 'Regional'],
      decisionMakerContactIds: ['contact-jon-bell'],
      contactCount: 1,
      lastActivityAt: '2026-07-07T18:20:00.000Z',
    },
    {
      id: 'org-signal-house',
      workspaceId: 'ws-beacon-lab',
      name: 'Signal House Collective',
      type: 'PARTNER',
      industry: 'Community media',
      website: 'https://signal-house.example.test',
      sponsorshipStage: 'Committed',
      estimatedValue: 60000,
      weightedValue: 60000,
      interestAreas: ['Storytelling', 'Community voice'],
      tags: ['Confirmed', 'Media partner'],
      decisionMakerContactIds: ['contact-amara-okafor'],
      contactCount: 1,
      lastActivityAt: '2026-07-05T19:10:00.000Z',
    },
    {
      id: 'org-riverbend-foods',
      workspaceId: 'ws-beacon-lab',
      name: 'Riverbend Community Foods',
      type: 'SPONSOR',
      industry: 'Food cooperative',
      website: 'https://riverbend-foods.example.test',
      sponsorshipStage: 'Declined',
      estimatedValue: 75000,
      weightedValue: 0,
      interestAreas: ['Food security'],
      tags: ['Do not contact', 'Closed'],
      decisionMakerContactIds: ['contact-theo-martin'],
      contactCount: 1,
      lastActivityAt: '2026-06-30T17:52:00.000Z',
    },
  ],
  contacts: [
    {
      id: 'contact-elena-ruiz',
      workspaceId: 'ws-beacon-lab',
      organizationId: 'org-lumina-mobility',
      type: 'SPONSOR',
      firstName: 'Elena',
      lastName: 'Ruiz',
      name: 'Elena Ruiz',
      email: 'elena.ruiz@example.test',
      phone: '+1-555-010-1024',
      title: 'Director of Community Partnerships',
      timezone: 'America/Los_Angeles',
      preferredChannel: 'EMAIL',
      source: 'Partner pipeline demo sheet',
      tags: ['Decision maker', 'Summit sponsor'],
      customFields: { sponsorshipTier: 'Beacon', relationshipOwner: 'Maya' },
      consentStatus: 'OPTED_IN',
      suppressedAt: null,
      externalId: 'DEMO-SP-1042',
      ownerId: 'user-maya-chen',
      campaignIds: ['campaign-pacific-summit'],
      status: 'FOLLOW_UP_DUE',
      lastInteractionAt: '2026-07-09T21:40:00.000Z',
      nextActionAt: '2026-07-10T16:15:00.000Z',
    },
    {
      id: 'contact-sam-rivera',
      workspaceId: 'ws-beacon-lab',
      organizationId: 'org-lumina-mobility',
      type: 'SPONSOR',
      firstName: 'Sam',
      lastName: 'Rivera',
      name: 'Sam Rivera',
      email: 'sam.rivera@example.test',
      phone: null,
      title: 'Community Programs Analyst',
      timezone: 'America/Los_Angeles',
      preferredChannel: 'EMAIL',
      source: 'Manual entry',
      tags: ['Influencer', 'Program contact'],
      customFields: { sponsorshipTier: 'Beacon', relationshipOwner: 'Maya' },
      consentStatus: 'IMPLIED',
      suppressedAt: null,
      externalId: 'DEMO-SP-1043',
      ownerId: 'user-maya-chen',
      campaignIds: ['campaign-pacific-summit'],
      status: 'AWAITING_RESPONSE',
      lastInteractionAt: '2026-07-08T17:05:00.000Z',
      nextActionAt: '2026-07-14T16:00:00.000Z',
    },
    {
      id: 'contact-marcus-lee',
      workspaceId: 'ws-beacon-lab',
      organizationId: 'org-harbor-civic',
      type: 'PARTNER',
      firstName: 'Marcus',
      lastName: 'Lee',
      name: 'Marcus Lee',
      email: 'marcus.lee@example.test',
      phone: '+1-555-010-1842',
      title: 'Partnerships Lead',
      timezone: 'America/Denver',
      preferredChannel: 'MEETING',
      source: 'CRM migration demo',
      tags: ['Renewal', 'Decision maker'],
      customFields: { renewalYear: 3, programRegion: 'Mountain' },
      consentStatus: 'OPTED_IN',
      suppressedAt: null,
      externalId: 'DEMO-PT-2007',
      ownerId: 'user-julian-reed',
      campaignIds: ['campaign-partner-renewal'],
      status: 'FOLLOW_UP_DUE',
      lastInteractionAt: '2026-07-10T14:18:00.000Z',
      nextActionAt: '2026-07-10T17:00:00.000Z',
    },
    {
      id: 'contact-priya-nair',
      workspaceId: 'ws-beacon-lab',
      organizationId: 'org-orbit-learning',
      type: 'SPONSOR',
      firstName: 'Priya',
      lastName: 'Nair',
      name: 'Priya Nair',
      email: 'priya.nair@example.test',
      phone: null,
      title: 'Social Impact Manager',
      timezone: 'America/New_York',
      preferredChannel: 'EMAIL',
      source: 'Event referral',
      tags: ['Education', 'New prospect'],
      customFields: { referralSource: 'Community Lab open house', budgetCycle: 'Q3' },
      consentStatus: 'OPTED_IN',
      suppressedAt: null,
      externalId: 'DEMO-SP-1098',
      ownerId: 'user-nadia-patel',
      campaignIds: ['campaign-pacific-summit'],
      status: 'FOLLOW_UP_DUE',
      lastInteractionAt: '2026-07-08T16:32:00.000Z',
      nextActionAt: '2026-07-14T13:15:00.000Z',
    },
    {
      id: 'contact-jon-bell',
      workspaceId: 'ws-beacon-lab',
      organizationId: 'org-verdant-grid',
      type: 'SPONSOR',
      firstName: 'Jon',
      lastName: 'Bell',
      name: 'Jon Bell',
      email: 'jon.bell@example.test',
      phone: '+1-555-010-2611',
      title: 'Regional Engagement Director',
      timezone: 'America/Chicago',
      preferredChannel: 'PHONE',
      source: 'Partner pipeline demo sheet',
      tags: ['Priority', 'Climate'],
      customFields: { interestScore: 72, relationshipOwner: 'Julian' },
      consentStatus: 'IMPLIED',
      suppressedAt: null,
      externalId: 'DEMO-SP-1114',
      ownerId: 'user-julian-reed',
      campaignIds: ['campaign-pacific-summit'],
      status: 'FOLLOW_UP_DUE',
      lastInteractionAt: '2026-07-07T18:20:00.000Z',
      nextActionAt: '2026-07-10T15:30:00.000Z',
    },
    {
      id: 'contact-amara-okafor',
      workspaceId: 'ws-beacon-lab',
      organizationId: 'org-signal-house',
      type: 'SPEAKER',
      firstName: 'Amara',
      lastName: 'Okafor',
      name: 'Amara Okafor',
      email: 'amara.okafor@example.test',
      phone: null,
      title: 'Editorial Director',
      timezone: 'America/New_York',
      preferredChannel: 'EMAIL',
      source: 'Speaker nomination form',
      tags: ['Confirmed speaker', 'Media partner'],
      customFields: { sessionTopic: 'Trust through community storytelling' },
      consentStatus: 'OPTED_IN',
      suppressedAt: null,
      externalId: 'DEMO-SK-3012',
      ownerId: 'user-nadia-patel',
      campaignIds: ['campaign-speaker-series'],
      status: 'ENGAGED',
      lastInteractionAt: '2026-07-05T19:10:00.000Z',
      nextActionAt: '2026-07-16T15:00:00.000Z',
    },
    {
      id: 'contact-theo-martin',
      workspaceId: 'ws-beacon-lab',
      organizationId: 'org-riverbend-foods',
      type: 'SPONSOR',
      firstName: 'Theo',
      lastName: 'Martin',
      name: 'Theo Martin',
      email: 'theo.martin@example.test',
      phone: null,
      title: 'Community Giving Manager',
      timezone: 'America/Los_Angeles',
      preferredChannel: 'EMAIL',
      source: 'Partner pipeline demo sheet',
      tags: ['Suppressed', 'Closed'],
      customFields: { closeReason: 'Budget committed elsewhere' },
      consentStatus: 'OPTED_OUT',
      suppressedAt: '2026-06-30T17:52:00.000Z',
      externalId: 'DEMO-SP-1120',
      ownerId: 'user-maya-chen',
      campaignIds: ['campaign-pacific-summit'],
      status: 'SUPPRESSED',
      lastInteractionAt: '2026-06-30T17:52:00.000Z',
      nextActionAt: null,
    },
    {
      id: 'contact-lina-park',
      workspaceId: 'ws-beacon-lab',
      organizationId: null,
      type: 'PARTICIPANT',
      firstName: 'Lina',
      lastName: 'Park',
      name: 'Lina Park',
      email: 'lina.park@example.test',
      phone: '+1-555-010-3904',
      title: 'Neighborhood Program Coordinator',
      timezone: 'America/Los_Angeles',
      preferredChannel: 'SMS',
      source: 'Summit registration demo',
      tags: ['Participant', 'Accessibility request'],
      customFields: {
        accessibilityRequest: 'Reserved front-row seating',
        registrationStatus: 'Confirmed',
      },
      consentStatus: 'OPTED_IN',
      suppressedAt: null,
      externalId: 'DEMO-PA-4021',
      ownerId: 'user-nadia-patel',
      campaignIds: ['campaign-speaker-series'],
      status: 'FOLLOW_UP_DUE',
      lastInteractionAt: '2026-07-04T16:25:00.000Z',
      nextActionAt: '2026-07-10T17:30:00.000Z',
    },
  ],
  campaigns: [
    {
      id: 'campaign-pacific-summit',
      workspaceId: 'ws-beacon-lab',
      name: 'Pacific Community Summit 2026',
      description: 'Secure aligned sponsors for the fictional September community summit.',
      type: 'SPONSORSHIP',
      objective: 'Present sponsorship opportunity',
      status: 'ACTIVE',
      ownerId: 'user-maya-chen',
      ownerName: 'Maya Chen',
      startAt: '2026-05-18T07:00:00.000Z',
      endAt: '2026-08-15T06:59:59.000Z',
      defaultTone: 'SPONSORSHIP_FOCUSED',
      contactIds: [
        'contact-elena-ruiz',
        'contact-sam-rivera',
        'contact-priya-nair',
        'contact-jon-bell',
        'contact-theo-martin',
      ],
      responseRate: 40.7,
      positiveResponseRate: 27.8,
      outreachSent: 54,
      responses: 22,
      followUpsDue: 3,
      estimatedValue: 495000,
      weightedValue: 199500,
    },
    {
      id: 'campaign-partner-renewal',
      workspaceId: 'ws-beacon-lab',
      name: 'Partner Renewal · Q3',
      description: 'Renew multi-year community-program partnerships before autumn planning.',
      type: 'PARTNERSHIP',
      objective: 'Re-engage',
      status: 'ACTIVE',
      ownerId: 'user-julian-reed',
      ownerName: 'Julian Reed',
      startAt: '2026-06-01T06:00:00.000Z',
      endAt: '2026-09-01T05:59:59.000Z',
      defaultTone: 'PARTNERSHIP_FOCUSED',
      contactIds: ['contact-marcus-lee'],
      responseRate: 39.5,
      positiveResponseRate: 25.6,
      outreachSent: 43,
      responses: 17,
      followUpsDue: 1,
      estimatedValue: 125000,
      weightedValue: 100000,
    },
    {
      id: 'campaign-speaker-series',
      workspaceId: 'ws-beacon-lab',
      name: 'Community Leaders Speaker Series',
      description: 'Confirm speakers and participant logistics for the summer learning series.',
      type: 'PARTICIPANT_OUTREACH',
      objective: 'Request information',
      status: 'ACTIVE',
      ownerId: 'user-nadia-patel',
      ownerName: 'Nadia Patel',
      startAt: '2026-06-15T07:00:00.000Z',
      endAt: '2026-08-29T06:59:59.000Z',
      defaultTone: 'WARM',
      contactIds: ['contact-amara-okafor', 'contact-lina-park'],
      responseRate: 34.5,
      positiveResponseRate: 17.2,
      outreachSent: 29,
      responses: 10,
      followUpsDue: 1,
      estimatedValue: 60000,
      weightedValue: 60000,
    },
  ],
  interactions: [
    {
      id: 'interaction-elena-outbound',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-pacific-summit',
      contactId: 'contact-elena-ruiz',
      channel: 'EMAIL',
      direction: 'OUTBOUND',
      subject: 'Pacific Community Summit partnership outline',
      bodyText:
        'Shared the reviewed sponsorship outline and invited questions about accessibility programming.',
      occurredAt: '2026-07-08T16:05:00.000Z',
      deliveryStatus: 'DELIVERED',
    },
    {
      id: 'interaction-elena-inbound',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-pacific-summit',
      contactId: 'contact-elena-ruiz',
      channel: 'EMAIL',
      direction: 'INBOUND',
      subject: 'Re: Pacific Community Summit partnership outline',
      bodyText:
        'Our team is interested. Please send the audience profile and the accessibility activation options.',
      occurredAt: '2026-07-09T21:40:00.000Z',
      deliveryStatus: 'RECEIVED',
    },
    {
      id: 'interaction-marcus-outbound',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-partner-renewal',
      contactId: 'contact-marcus-lee',
      channel: 'EMAIL',
      direction: 'OUTBOUND',
      subject: 'Planning our next neighborhood leadership cycle',
      bodyText:
        'Asked whether Harbor Civic would like to review the next cycle’s shared outcomes and renewal scope.',
      occurredAt: '2026-07-09T15:10:00.000Z',
      deliveryStatus: 'DELIVERED',
    },
    {
      id: 'interaction-marcus-inbound',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-partner-renewal',
      contactId: 'contact-marcus-lee',
      channel: 'EMAIL',
      direction: 'INBOUND',
      subject: 'Re: Planning our next neighborhood leadership cycle',
      bodyText:
        'Yes, let’s meet next week. Tuesday morning or Thursday after lunch would work for our team.',
      occurredAt: '2026-07-10T14:18:00.000Z',
      deliveryStatus: 'RECEIVED',
    },
    {
      id: 'interaction-priya-outbound',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-pacific-summit',
      contactId: 'contact-priya-nair',
      channel: 'EMAIL',
      direction: 'OUTBOUND',
      subject: 'Digital access track at the Pacific Community Summit',
      bodyText: 'Introduced the digital access track and offered a concise sponsor overview.',
      occurredAt: '2026-07-08T16:32:00.000Z',
      deliveryStatus: 'DELIVERED',
    },
    {
      id: 'interaction-jon-outbound',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-pacific-summit',
      contactId: 'contact-jon-bell',
      channel: 'PHONE',
      direction: 'OUTBOUND',
      subject: 'Summit resilience track check-in',
      bodyText: 'Voicemail left with a callback number; no sponsorship terms were discussed.',
      occurredAt: '2026-07-07T18:20:00.000Z',
      deliveryStatus: 'DELIVERED',
    },
    {
      id: 'interaction-amara-inbound',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-speaker-series',
      contactId: 'contact-amara-okafor',
      channel: 'EMAIL',
      direction: 'INBOUND',
      subject: 'Speaker session confirmed',
      bodyText: 'Confirmed the session and requested the final run-of-show when available.',
      occurredAt: '2026-07-05T19:10:00.000Z',
      deliveryStatus: 'RECEIVED',
    },
    {
      id: 'interaction-theo-inbound',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-pacific-summit',
      contactId: 'contact-theo-martin',
      channel: 'EMAIL',
      direction: 'INBOUND',
      subject: 'Re: Pacific Community Summit',
      bodyText:
        'We have committed this year’s budget elsewhere. Please remove me from additional sponsor outreach.',
      occurredAt: '2026-06-30T17:52:00.000Z',
      deliveryStatus: 'RECEIVED',
    },
    {
      id: 'interaction-lina-outbound',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-speaker-series',
      contactId: 'contact-lina-park',
      channel: 'SMS',
      direction: 'OUTBOUND',
      subject: 'Registration logistics',
      bodyText:
        'Sent a reviewed registration confirmation and asked whether the seating note was accurate.',
      occurredAt: '2026-07-04T16:25:00.000Z',
      deliveryStatus: 'DELIVERED',
    },
  ],
  responses: [
    {
      id: 'response-elena',
      workspaceId: 'ws-beacon-lab',
      interactionId: 'interaction-elena-inbound',
      classification: 'NEEDS_MORE_INFORMATION',
      sentiment: 'POSITIVE',
      urgency: 'HIGH',
      responseTimeMinutes: 1775,
      humanReviewed: true,
      keyQuestion: 'Can Faro share audience profile and accessibility activation options?',
      recommendedNextAction:
        'Send the approved audience profile and two accessibility activation examples.',
    },
    {
      id: 'response-marcus',
      workspaceId: 'ws-beacon-lab',
      interactionId: 'interaction-marcus-inbound',
      classification: 'MEETING_REQUESTED',
      sentiment: 'POSITIVE',
      urgency: 'HIGH',
      responseTimeMinutes: 1388,
      humanReviewed: true,
      keyQuestion: 'Which offered meeting time should the team confirm?',
      recommendedNextAction:
        'Offer Tuesday at 10:00 AM Mountain time and include a brief renewal agenda.',
    },
    {
      id: 'response-amara',
      workspaceId: 'ws-beacon-lab',
      interactionId: 'interaction-amara-inbound',
      classification: 'INTERESTED',
      sentiment: 'POSITIVE',
      urgency: 'NORMAL',
      responseTimeMinutes: 244,
      humanReviewed: true,
      keyQuestion: 'When will the final run-of-show be ready?',
      recommendedNextAction: 'Confirm the delivery date for the run-of-show.',
    },
    {
      id: 'response-theo',
      workspaceId: 'ws-beacon-lab',
      interactionId: 'interaction-theo-inbound',
      classification: 'UNSUBSCRIBE',
      sentiment: 'NEUTRAL',
      urgency: 'URGENT',
      responseTimeMinutes: 507,
      humanReviewed: true,
      keyQuestion: null,
      recommendedNextAction: 'Keep the contact suppressed and close the sponsor opportunity.',
    },
  ],
  followUps: [
    {
      id: 'followup-elena-proposal',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-pacific-summit',
      campaignName: 'Pacific Community Summit 2026',
      contactId: 'contact-elena-ruiz',
      contactName: 'Elena Ruiz',
      organizationName: 'Lumina Mobility Cooperative',
      assignedUserId: 'user-maya-chen',
      assignedUserName: 'Maya Chen',
      status: 'OPEN',
      priority: 'URGENT',
      dueAt: '2026-07-10T16:15:00.000Z',
      reason: 'Requested audience and accessibility activation details.',
      lastResponseSummary:
        'Interested; needs two specific supporting details before internal review.',
      recommendedNextAction: 'Send the approved audience profile and activation examples.',
      recommendationId: 'recommendation-elena',
      bobRequestId: 'bob-request-elena',
      draftId: 'bob-draft-elena-demo',
      lastNotificationAt: '2026-07-10T14:45:00.000Z',
      completedAt: null,
    },
    {
      id: 'followup-marcus-meeting',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-partner-renewal',
      campaignName: 'Partner Renewal · Q3',
      contactId: 'contact-marcus-lee',
      contactName: 'Marcus Lee',
      organizationName: 'Harbor Civic Foundation',
      assignedUserId: 'user-julian-reed',
      assignedUserName: 'Julian Reed',
      status: 'OPEN',
      priority: 'HIGH',
      dueAt: '2026-07-10T17:00:00.000Z',
      reason: 'Meeting requested with two availability windows.',
      lastResponseSummary: 'Available Tuesday morning or Thursday after lunch.',
      recommendedNextAction: 'Confirm Tuesday at 10:00 AM Mountain and send a short agenda.',
      recommendationId: 'recommendation-marcus',
      bobRequestId: 'bob-request-marcus',
      draftId: null,
      lastNotificationAt: '2026-07-10T14:30:00.000Z',
      completedAt: null,
    },
    {
      id: 'followup-priya-materials',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-pacific-summit',
      campaignName: 'Pacific Community Summit 2026',
      contactId: 'contact-priya-nair',
      contactName: 'Priya Nair',
      organizationName: 'Orbit Learning Studio',
      assignedUserId: 'user-nadia-patel',
      assignedUserName: 'Nadia Patel',
      status: 'OPEN',
      priority: 'HIGH',
      dueAt: '2026-07-10T13:30:00.000Z',
      reason: 'No response after the initial introduction; campaign deadline is approaching.',
      lastResponseSummary: 'No response recorded.',
      recommendedNextAction:
        'Share the concise education-track overview at the next recommended window.',
      recommendationId: 'recommendation-priya',
      bobRequestId: 'bob-request-priya',
      draftId: 'bob-draft-priya-demo',
      lastNotificationAt: '2026-07-10T13:15:00.000Z',
      completedAt: null,
    },
    {
      id: 'followup-jon-checkin',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-pacific-summit',
      campaignName: 'Pacific Community Summit 2026',
      contactId: 'contact-jon-bell',
      contactName: 'Jon Bell',
      organizationName: 'Verdant Grid Works',
      assignedUserId: 'user-julian-reed',
      assignedUserName: 'Julian Reed',
      status: 'OPEN',
      priority: 'MEDIUM',
      dueAt: '2026-07-10T15:30:00.000Z',
      reason: 'Voicemail has not received a response after three days.',
      lastResponseSummary: 'No response recorded.',
      recommendedNextAction:
        'Use email instead of another phone call and reference the resilience track.',
      recommendationId: 'recommendation-jon',
      bobRequestId: null,
      draftId: null,
      lastNotificationAt: null,
      completedAt: null,
    },
    {
      id: 'followup-lina-confirmation',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-speaker-series',
      campaignName: 'Community Leaders Speaker Series',
      contactId: 'contact-lina-park',
      contactName: 'Lina Park',
      organizationName: 'Independent participant',
      assignedUserId: 'user-nadia-patel',
      assignedUserName: 'Nadia Patel',
      status: 'SNOOZED',
      priority: 'MEDIUM',
      dueAt: '2026-07-10T17:30:00.000Z',
      reason: 'Accessibility seating confirmation is still pending.',
      lastResponseSummary: 'No response recorded.',
      recommendedNextAction: 'Send one concise confirmation message, then pause outreach.',
      recommendationId: 'recommendation-lina',
      bobRequestId: null,
      draftId: null,
      lastNotificationAt: '2026-07-09T17:00:00.000Z',
      completedAt: null,
    },
    {
      id: 'followup-amara-run-show',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-speaker-series',
      campaignName: 'Community Leaders Speaker Series',
      contactId: 'contact-amara-okafor',
      contactName: 'Amara Okafor',
      organizationName: 'Signal House Collective',
      assignedUserId: 'user-nadia-patel',
      assignedUserName: 'Nadia Patel',
      status: 'COMPLETED',
      priority: 'LOW',
      dueAt: '2026-07-07T16:00:00.000Z',
      reason: 'Confirm when the final run-of-show will be shared.',
      lastResponseSummary: 'Speaker confirmed and requested the final run-of-show.',
      recommendedNextAction: 'Send the committed delivery date.',
      recommendationId: null,
      bobRequestId: null,
      draftId: null,
      lastNotificationAt: '2026-07-07T15:30:00.000Z',
      completedAt: '2026-07-07T16:08:00.000Z',
    },
  ],
  recommendations: [
    {
      id: 'recommendation-elena',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-pacific-summit',
      contactId: 'contact-elena-ruiz',
      contactName: 'Elena Ruiz',
      organizationName: 'Lumina Mobility Cooperative',
      recommendedAt: '2026-07-10T16:15:00.000Z',
      alternativeWindows: ['2026-07-13T16:00:00.000Z', '2026-07-14T17:15:00.000Z'],
      confidence: 0.91,
      score: 88,
      dataSufficiency: 'HIGH',
      reasonCodes: ['CONTACT_REPLY_HISTORY', 'EMAIL_MORNING_WINDOW', 'CAMPAIGN_DEADLINE'],
      explanation:
        'Elena has replied most often between 9:00 and 10:30 AM local time; the proposal review date adds urgency.',
      algorithmVersion: 'faro-window-v1.0.0',
      status: 'PROPOSED',
    },
    {
      id: 'recommendation-marcus',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-partner-renewal',
      contactId: 'contact-marcus-lee',
      contactName: 'Marcus Lee',
      organizationName: 'Harbor Civic Foundation',
      recommendedAt: '2026-07-10T17:00:00.000Z',
      alternativeWindows: ['2026-07-10T19:30:00.000Z', '2026-07-13T16:30:00.000Z'],
      confidence: 0.86,
      score: 84,
      dataSufficiency: 'HIGH',
      reasonCodes: ['RECENT_POSITIVE_RESPONSE', 'CONTACT_AVAILABILITY', 'WITHIN_QUIET_HOURS'],
      explanation:
        'A prompt confirmation matches the explicit meeting request and remains inside both users’ working hours.',
      algorithmVersion: 'faro-window-v1.0.0',
      status: 'ACCEPTED',
    },
    {
      id: 'recommendation-priya',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-pacific-summit',
      contactId: 'contact-priya-nair',
      contactName: 'Priya Nair',
      organizationName: 'Orbit Learning Studio',
      recommendedAt: '2026-07-14T13:15:00.000Z',
      alternativeWindows: ['2026-07-15T14:00:00.000Z', '2026-07-16T13:30:00.000Z'],
      confidence: 0.68,
      score: 71,
      dataSufficiency: 'MEDIUM',
      reasonCodes: ['COHORT_REPLY_HISTORY', 'PREFERRED_CHANNEL', 'AVOID_WEEKEND'],
      explanation:
        'Contact history is sparse, so the window uses the education-sponsor cohort and Priya’s Eastern timezone.',
      algorithmVersion: 'faro-window-v1.0.0',
      status: 'PROPOSED',
    },
    {
      id: 'recommendation-jon',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-pacific-summit',
      contactId: 'contact-jon-bell',
      contactName: 'Jon Bell',
      organizationName: 'Verdant Grid Works',
      recommendedAt: '2026-07-10T15:30:00.000Z',
      alternativeWindows: ['2026-07-13T15:00:00.000Z', '2026-07-14T16:00:00.000Z'],
      confidence: 0.54,
      score: 62,
      dataSufficiency: 'LOW',
      reasonCodes: ['CHANNEL_SWITCH', 'UNANSWERED_MESSAGE', 'COHORT_REPLY_HISTORY'],
      explanation:
        'There is not enough contact history for a strong prediction; switch from phone to a concise email.',
      algorithmVersion: 'faro-window-v1.0.0',
      status: 'PROPOSED',
    },
    {
      id: 'recommendation-lina',
      workspaceId: 'ws-beacon-lab',
      campaignId: 'campaign-speaker-series',
      contactId: 'contact-lina-park',
      contactName: 'Lina Park',
      organizationName: 'Independent participant',
      recommendedAt: '2026-07-10T17:30:00.000Z',
      alternativeWindows: ['2026-07-13T17:00:00.000Z'],
      confidence: 0.43,
      score: 55,
      dataSufficiency: 'LOW',
      reasonCodes: ['SPARSE_HISTORY', 'PREFERRED_CHANNEL', 'FREQUENCY_GUARD'],
      explanation:
        'Only one delivery event is available. The recommendation favors the preferred channel and limits frequency.',
      algorithmVersion: 'faro-window-v1.0.0',
      status: 'SNOOZED',
    },
  ],
  bobRequests: [
    {
      id: 'bob-request-elena',
      workspaceId: 'ws-beacon-lab',
      contactId: 'contact-elena-ruiz',
      campaignId: 'campaign-pacific-summit',
      followUpTaskId: 'followup-elena-proposal',
      type: 'OUTREACH_DRAFT',
      promptVersion: 'outreach-draft.v1',
      status: 'COMPLETED',
      requestedBy: 'user-maya-chen',
      requestedAt: '2026-07-10T12:04:00.000Z',
      completedAt: '2026-07-10T12:05:00.000Z',
      errorCode: null,
      resultProvenance: 'DEMO_DRAFT',
    },
    {
      id: 'bob-request-marcus',
      workspaceId: 'ws-beacon-lab',
      contactId: 'contact-marcus-lee',
      campaignId: 'campaign-partner-renewal',
      followUpTaskId: 'followup-marcus-meeting',
      type: 'OUTREACH_DRAFT',
      promptVersion: 'outreach-draft.v1',
      status: 'AWAITING_BOB',
      requestedBy: 'user-julian-reed',
      requestedAt: '2026-07-10T14:25:00.000Z',
      completedAt: null,
      errorCode: null,
      resultProvenance: null,
    },
    {
      id: 'bob-request-priya',
      workspaceId: 'ws-beacon-lab',
      contactId: 'contact-priya-nair',
      campaignId: 'campaign-pacific-summit',
      followUpTaskId: 'followup-priya-materials',
      type: 'OUTREACH_DRAFT',
      promptVersion: 'outreach-draft.v1',
      status: 'COMPLETED',
      requestedBy: 'user-nadia-patel',
      requestedAt: '2026-07-09T16:10:00.000Z',
      completedAt: '2026-07-09T16:11:00.000Z',
      errorCode: null,
      resultProvenance: 'DEMO_DRAFT',
    },
    {
      id: 'bob-request-jon-failed',
      workspaceId: 'ws-beacon-lab',
      contactId: 'contact-jon-bell',
      campaignId: 'campaign-pacific-summit',
      followUpTaskId: 'followup-jon-checkin',
      type: 'OUTREACH_DRAFT',
      promptVersion: 'outreach-draft.v1',
      status: 'FAILED',
      requestedBy: 'user-julian-reed',
      requestedAt: '2026-07-09T18:00:00.000Z',
      completedAt: '2026-07-09T18:00:01.000Z',
      errorCode: 'BOB_MCP_NOT_CONFIGURED',
      resultProvenance: null,
    },
  ],
  bobDrafts: [
    {
      id: 'bob-draft-elena-demo',
      workspaceId: 'ws-beacon-lab',
      generationRequestId: 'bob-request-elena',
      subject: 'Audience and accessibility details for your review',
      bodyText:
        'Hi Elena,\n\nThank you for your interest. I’m sharing the approved audience profile and two accessibility activation examples your team can review. Would a 20-minute conversation next week be useful after you have had a chance to look them over?\n\nBest,\nMaya',
      rationale:
        'Acknowledges the specific request, supplies only approved material, and offers a low-pressure next step.',
      recommendedNextAction:
        'Attach the approved audience profile and accessibility activation one-page document before sending.',
      suggestedFollowUpAt: '2026-07-14T17:15:00.000Z',
      confidence: 0.82,
      riskFlags: ['VERIFY_ATTACHMENTS_BEFORE_SEND'],
      sourceRecordIds: [
        'contact-elena-ruiz',
        'campaign-pacific-summit',
        'interaction-elena-inbound',
      ],
      generatedAt: '2026-07-10T12:05:00.000Z',
      approvalStatus: 'APPROVED',
      approvedBy: 'user-maya-chen',
      approvedAt: '2026-07-10T12:20:00.000Z',
      provenance: 'DEMO_DRAFT',
      provenanceLabel: 'Demo draft',
      promptVersion: 'outreach-draft.v1',
    },
    {
      id: 'bob-draft-priya-demo',
      workspaceId: 'ws-beacon-lab',
      generationRequestId: 'bob-request-priya',
      subject: 'A concise look at the summit’s digital access track',
      bodyText:
        'Hi Priya,\n\nI wanted to follow up with a short overview of the Pacific Community Summit’s digital access track. Orbit Learning Studio’s mentorship focus may align with the participant goals in the attached approved brief. If it is relevant, would you be open to a short introduction next week?\n\nBest,\nNadia',
      rationale:
        'Uses the documented education and mentorship interests while avoiding unverified claims about fit or budget.',
      recommendedNextAction:
        'Review the attachment and edit the partnership-fit sentence before approval.',
      suggestedFollowUpAt: '2026-07-16T13:30:00.000Z',
      confidence: 0.67,
      riskFlags: ['SPARSE_CONTACT_HISTORY', 'CONFIRM_ATTACHMENT'],
      sourceRecordIds: ['contact-priya-nair', 'org-orbit-learning', 'campaign-pacific-summit'],
      generatedAt: '2026-07-09T16:11:00.000Z',
      approvalStatus: 'PENDING_REVIEW',
      approvedBy: null,
      approvedAt: null,
      provenance: 'DEMO_DRAFT',
      provenanceLabel: 'Demo draft',
      promptVersion: 'outreach-draft.v1',
    },
  ],
  sheetConnections: [
    {
      id: 'sheet-connection-demo-pipeline',
      workspaceId: 'ws-beacon-lab',
      spreadsheetId: 'demo-not-connected',
      worksheetId: 'Sponsors',
      displayName: 'Demo · Partner pipeline',
      syncDirection: 'IMPORT',
      schedule: 'Manual dry run',
      lastSyncedAt: '2026-07-10T13:42:00.000Z',
      status: 'NEEDS_AUTH',
      writeBackEnabled: false,
    },
  ],
  sheetSyncs: [
    {
      id: 'sheet-sync-demo-latest',
      workspaceId: 'ws-beacon-lab',
      sheetConnectionId: 'sheet-connection-demo-pipeline',
      status: 'DRY_RUN',
      startedAt: '2026-07-10T13:41:12.000Z',
      completedAt: '2026-07-10T13:42:00.000Z',
      rowsRead: 84,
      rowsCreated: 0,
      rowsUpdated: 0,
      rowsSkipped: 82,
      rowsFailed: 2,
      errorSummary: 'Two demo rows have missing email values. Dry run made no database changes.',
      dryRun: true,
    },
    {
      id: 'sheet-sync-demo-mapping',
      workspaceId: 'ws-beacon-lab',
      sheetConnectionId: 'sheet-connection-demo-pipeline',
      status: 'DRY_RUN',
      startedAt: '2026-07-03T15:00:00.000Z',
      completedAt: '2026-07-03T15:00:31.000Z',
      rowsRead: 80,
      rowsCreated: 0,
      rowsUpdated: 0,
      rowsSkipped: 80,
      rowsFailed: 0,
      errorSummary: null,
      dryRun: true,
    },
  ],
  notifications: [
    {
      id: 'notification-elena-in-app',
      workspaceId: 'ws-beacon-lab',
      userId: 'user-maya-chen',
      followUpTaskId: 'followup-elena-proposal',
      channel: 'IN_APP',
      status: 'SENT',
      scheduledFor: '2026-07-10T14:45:00.000Z',
      sentAt: '2026-07-10T14:45:00.000Z',
      deduplicationKey: 'followup-elena-proposal:in-app:2026-07-10',
      errorCode: null,
      title: 'Elena Ruiz follow-up is due',
      message: 'Send the requested audience profile and accessibility activation examples.',
      isRead: false,
      deliveryLabel: 'In-app notification',
    },
    {
      id: 'notification-priya-email-preview',
      workspaceId: 'ws-beacon-lab',
      userId: 'user-nadia-patel',
      followUpTaskId: 'followup-priya-materials',
      channel: 'EMAIL',
      status: 'PREVIEWED',
      scheduledFor: '2026-07-10T13:15:00.000Z',
      sentAt: '2026-07-10T13:15:02.000Z',
      deduplicationKey: 'followup-priya-materials:email-preview:2026-07-10',
      errorCode: null,
      title: 'Preview: Priya Nair follow-up',
      message: 'Development preview only. No external email was delivered.',
      isRead: true,
      deliveryLabel: 'Development email preview',
    },
    {
      id: 'notification-marcus-in-app',
      workspaceId: 'ws-beacon-lab',
      userId: 'user-julian-reed',
      followUpTaskId: 'followup-marcus-meeting',
      channel: 'IN_APP',
      status: 'SENT',
      scheduledFor: '2026-07-10T14:30:00.000Z',
      sentAt: '2026-07-10T14:30:00.000Z',
      deduplicationKey: 'followup-marcus-meeting:in-app:2026-07-10',
      errorCode: null,
      title: 'Meeting request received',
      message: 'Marcus Lee offered Tuesday morning or Thursday afternoon.',
      isRead: false,
      deliveryLabel: 'In-app notification',
    },
  ],
  analytics: {
    responseRateTrend: [
      {
        period: 'Jun 1',
        outreachSent: 17,
        responses: 5,
        responseRate: 29.4,
        positiveResponseRate: 17.6,
      },
      {
        period: 'Jun 8',
        outreachSent: 19,
        responses: 7,
        responseRate: 36.8,
        positiveResponseRate: 21.1,
      },
      {
        period: 'Jun 15',
        outreachSent: 21,
        responses: 8,
        responseRate: 38.1,
        positiveResponseRate: 23.8,
      },
      {
        period: 'Jun 22',
        outreachSent: 20,
        responses: 8,
        responseRate: 40,
        positiveResponseRate: 25,
      },
      {
        period: 'Jun 29',
        outreachSent: 24,
        responses: 10,
        responseRate: 41.7,
        positiveResponseRate: 29.2,
      },
      {
        period: 'Jul 6',
        outreachSent: 25,
        responses: 11,
        responseRate: 44,
        positiveResponseRate: 28,
      },
    ],
    outreachHeatmap: [
      { day: 'Monday', hour: 9, responseRate: 34, sampleSize: 18, strength: 'MEDIUM' },
      { day: 'Monday', hour: 14, responseRate: 39, sampleSize: 13, strength: 'MEDIUM' },
      { day: 'Tuesday', hour: 9, responseRate: 46, sampleSize: 24, strength: 'HIGH' },
      { day: 'Tuesday', hour: 11, responseRate: 43, sampleSize: 21, strength: 'HIGH' },
      { day: 'Wednesday', hour: 10, responseRate: 41, sampleSize: 22, strength: 'HIGH' },
      { day: 'Wednesday', hour: 15, responseRate: 27, sampleSize: 11, strength: 'LOW' },
      { day: 'Thursday', hour: 9, responseRate: 44, sampleSize: 19, strength: 'HIGH' },
      { day: 'Thursday', hour: 13, responseRate: 36, sampleSize: 14, strength: 'MEDIUM' },
      { day: 'Friday', hour: 10, responseRate: 31, sampleSize: 16, strength: 'MEDIUM' },
      { day: 'Friday', hour: 15, responseRate: 18, sampleSize: 9, strength: 'LOW' },
    ],
    funnel: [
      { label: 'Outreach planned', value: 142, rateFromPrevious: 100 },
      { label: 'Delivered', value: 126, rateFromPrevious: 88.7 },
      { label: 'Responded', value: 49, rateFromPrevious: 38.9 },
      { label: 'Positive signal', value: 31, rateFromPrevious: 63.3 },
      { label: 'Meeting or proposal', value: 14, rateFromPrevious: 45.2 },
    ],
    channelPerformance: [
      { channel: 'EMAIL', outreachSent: 93, responseRate: 40.9, medianResponseMinutes: 318 },
      { channel: 'PHONE', outreachSent: 15, responseRate: 26.7, medianResponseMinutes: 690 },
      { channel: 'SMS', outreachSent: 11, responseRate: 45.5, medianResponseMinutes: 74 },
      { channel: 'MEETING', outreachSent: 7, responseRate: 28.6, medianResponseMinutes: 1440 },
    ],
    pipeline: [
      { stage: 'Prospecting', order: 1, organizationCount: 0, value: 0, weightedValue: 0 },
      { stage: 'Qualified', order: 2, organizationCount: 1, value: 90000, weightedValue: 22500 },
      { stage: 'Contacted', order: 3, organizationCount: 1, value: 150000, weightedValue: 60000 },
      { stage: 'Engaged', order: 4, organizationCount: 0, value: 0, weightedValue: 0 },
      { stage: 'Proposal', order: 5, organizationCount: 1, value: 180000, weightedValue: 117000 },
      {
        stage: 'Negotiation',
        order: 6,
        organizationCount: 1,
        value: 125000,
        weightedValue: 100000,
      },
      { stage: 'Committed', order: 7, organizationCount: 1, value: 60000, weightedValue: 60000 },
      { stage: 'Declined', order: 8, organizationCount: 1, value: 75000, weightedValue: 0 },
    ],
    campaignComparison: [
      {
        campaignId: 'campaign-pacific-summit',
        campaignName: 'Pacific Community Summit 2026',
        outreachSent: 54,
        responseRate: 40.7,
        positiveResponseRate: 27.8,
        followUpsDue: 3,
      },
      {
        campaignId: 'campaign-partner-renewal',
        campaignName: 'Partner Renewal · Q3',
        outreachSent: 43,
        responseRate: 39.5,
        positiveResponseRate: 25.6,
        followUpsDue: 1,
      },
      {
        campaignId: 'campaign-speaker-series',
        campaignName: 'Community Leaders Speaker Series',
        outreachSent: 29,
        responseRate: 34.5,
        positiveResponseRate: 17.2,
        followUpsDue: 1,
      },
    ],
    medianFirstResponseMinutes: 322,
    followUpConversionRate: 31.4,
    dataQuality: {
      validEmailRate: 98.6,
      timezoneCoverage: 93.2,
      deduplicatedRecords: 14,
      syncFailureRate: 2.4,
    },
    textualSummary:
      'Response rate improved in five of the last six weeks. Tuesday and Thursday mornings are the strongest observed email windows. The Pacific Community Summit carries the most active value and three due follow-ups. Heatmap samples remain small for Friday afternoons.',
  },
  integrationStatus: {
    bob: {
      mcpConfigured: false,
      runtimeAdapterConfigured: false,
      status: 'AWAITING_CONFIGURATION',
      lastSuccessfulOperationAt: null,
      promptTemplateVersion: 'outreach-draft.v1',
      lastMcpSyncAt: null,
      actionRequired: 'Configure the Faro MCP server in IBM Bob to process awaiting requests.',
    },
    googleSheets: {
      oauthConfigured: false,
      status: 'DEMO_DATA',
      lastSyncedAt: null,
      nextScheduledSyncAt: null,
      actionRequired: 'Add Google OAuth credentials before connecting a real spreadsheet.',
    },
    notifications: {
      inApp: 'AVAILABLE',
      email: 'PREVIEW_ONLY',
      webPush: 'UNAVAILABLE',
      sms: 'UNAVAILABLE',
    },
  },
  auditEvents: [
    {
      id: 'audit-bob-request-marcus',
      workspaceId: 'ws-beacon-lab',
      actorType: 'USER',
      actorId: 'user-julian-reed',
      action: 'bob_generation.requested',
      entityType: 'BobGenerationRequest',
      entityId: 'bob-request-marcus',
      summary: 'Created an awaiting IBM Bob request with prompt version outreach-draft.v1.',
      occurredAt: '2026-07-10T14:25:00.000Z',
    },
    {
      id: 'audit-sheet-dry-run',
      workspaceId: 'ws-beacon-lab',
      actorType: 'USER',
      actorId: 'user-maya-chen',
      action: 'sheet_sync.dry_run_completed',
      entityType: 'SheetSyncRun',
      entityId: 'sheet-sync-demo-latest',
      summary: 'Validated 84 demo rows without writing records; two rows need review.',
      occurredAt: '2026-07-10T13:42:00.000Z',
    },
    {
      id: 'audit-demo-draft-approved',
      workspaceId: 'ws-beacon-lab',
      actorType: 'USER',
      actorId: 'user-maya-chen',
      action: 'demo_draft.approved',
      entityType: 'BobDraft',
      entityId: 'bob-draft-elena-demo',
      summary: 'Approved a deterministic Demo draft. No external message was sent.',
      occurredAt: '2026-07-10T12:20:00.000Z',
    },
  ],
};
